// src/components/Nav.tsx
import React, { MouseEvent, useContext, useEffect, useState } from 'react';
import ThemeContext from '../theme-context';

interface LinkProps {
  href: string;
  children?: React.ReactNode;
}

const Link = ({ href, children }: LinkProps) => {
  const { setExpanded } = useContext(NavContext);
  
  return (
    <li className="nav-item">
      {href.startsWith('#') ?
        <a className="nav-link" href={href} onClick={() => setExpanded(false)}>{children}</a>
      :
        <a className="nav-link" href={href} target="_blank">{children}</a>
      }
    </li>
  );
}

const NavContext = React.createContext<{ expanded: boolean, setExpanded: (expanded: boolean) => void }>({ expanded: false, setExpanded: () => { return; } });

const Nav = () => {
  const [expanded, setExpanded] = useState(false);
  const [opaque, setOpaque] = useState(false);
  const { theme, toggleTheme } = useContext(ThemeContext);

  useEffect(() => {
    const handleScroll = () => setOpaque(document.documentElement.scrollTop > 0);

    window.addEventListener('scroll', handleScroll);

    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const toggleNav = (e: MouseEvent) => {
    e.preventDefault();
    setExpanded(expanded => !expanded);
  };

  return (
    <NavContext.Provider value={{ expanded: expanded, setExpanded: (expanded) => setExpanded(expanded) }}>
      <nav className={"navbar navbar-expand-lg" + (expanded ? ' navbar-expanded' : '') + (opaque ? ' navbar-opaque' : '')}>
        <div className="container">
          <a className="navbar-brand" href="#">
            <img src={theme === 'light' ? './favicon.png' : './favicon-white.png' } width="30" height="30" className="d-inline-block align-top" alt="home" />
          </a>
          <button className="nav-toggle" onClick={toggleNav} aria-label="menu">
            <span className="icon"></span>
          </button>
          <div className="pull-right collapse navbar-collapse d-flex flex-row-reverse">
            <ul className="navbar-nav">
              <Link href="#about">About</Link>
              <Link href="#projects">Projects</Link>
              <Link href="#photos">Photos</Link>
              <Link href="Resume.pdf">Resume</Link>
              <li className="nav-item theme-toggle">
                <span className={'fa fa-lg ' + (theme === 'light' ? 'fa-sun' : 'fa-moon')} onClick={toggleTheme}></span>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </NavContext.Provider>
  );
}

export default Nav;

// src/lib/nav/Nav.svelte
<script lang="ts">
  import { getContext, setContext } from 'svelte';
  import { get, type Writable } from 'svelte/store';
  import type { Theme } from '../types';
  import Link from './Link.svelte';

  let y: number;
  let expanded = false;

  const theme: Writable<Theme> = getContext('theme');
  let darkMode = get(theme) === 'dark';
  theme.subscribe((value) => {
    darkMode = value === 'dark';
  });

  function toggleExpand() {
    expanded = !expanded;
    if (expanded) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'auto';
    }
  }

  function close() {
    expanded = false;
    document.body.style.overflow = 'auto';
  }

  setContext('closeNav', close);

  function toggleTheme() {
    theme.update((value) => {
      return value === 'light' ? 'dark' : 'light';
    });
  }
</script>

<svelte:window bind:scrollY={y} />

<header class:expanded class:scrolled={y}>
  <nav class="container">
    <div class="header">
      <a class="icon" href="/"><img src={darkMode ? 'favicon-white.png' : 'favicon.png'} alt="js" /></a>
      <button class="hamburger" on:click={toggleExpand} aria-label="nav menu"></button>
    </div>
    <ul>
      <Link href="/">about me</Link>
      <Link href="/experience">experience</Link>
      <Link href="/projects">projects</Link>
      <Link href="/resume.pdf" target="_blank">resume</Link>
      <Link href="/photos">photos</Link>
      <li>
        <button class="theme-toggle" on:click={toggleTheme} aria-label="theme toggle">
          <span class={'fas ' + (darkMode ? 'fa-moon' : 'fa-sun')}></span>
        </button>
      </li>
    </ul>
  </nav>
</header>

<style>
  header {
    position: sticky;
    top: 0;
    background-color: transparent;
    transition: 0.3s;
    padding: 10px 0;
    z-index: 1;

    &.scrolled {
      background-color: var(--overlay1);
      box-shadow: 0 1px 10px var(--box-shadow);
      padding: 5px 0;
    }
  }

  nav {
    display: flex;
  }

  .icon {
    display: flex;
    margin: auto 0;
  }

  .icon img {
    height: 2rem;
  }

  .theme-toggle {
    border: none;
    background: none;
    cursor: pointer;
    display: flex;
  }

  .theme-toggle span:hover {
    color: var(--text1);
  }

  ul {
    list-style: none;
    display: flex;
    flex-direction: row;
    gap: 1em;
    margin-left: auto;
  }

  li {
    display: flex;
    flex-direction: column;
    justify-content: center;
  }

  .hamburger {
    display: none;
    background: none;
    border: none;
    position: relative;

    &::before,
    &&::after {
      display: block;
      content: '';
      width: 1.5em;
      height: 2px;
      background-color: var(--text2);
      transition: 0.3s;
    }

    &::before {
      transform: translateY(-0.25em);
    }

    &::after {
      transform: translateY(0.25em);
    }
  }

  .header {
    display: flex;
    flex-direction: row;
  }

  @media screen and (max-width: 575px) {
    .hamburger {
      display: block;
      margin-left: auto;
    }

    .header {
      width: 100%;
    }

    .expanded .hamburger::before {
      transform: rotate(45deg) translateY(1px);
    }

    .expanded .hamburger::after {
      transform: rotate(-45deg) translateY(-1px);
    }

    ul {
      display: none;
      height: 0;
      transition: 0.3s;
    }

    .expanded {
      height: 100vh;
      width: 100%;
      background-color: var(--overlay1);
    }

    .expanded nav {
      flex-direction: column;
    }

    .expanded ul {
      display: flex;
      margin: 0;
      padding: 1rem;
      flex-direction: column;
      gap: 1.5rem;
      height: 100%;
    }

    .expanded ul a {
      font-size: x-large;
    }
  }
</style>
