// src/App.tsx
import { useState, useEffect } from 'react';
import Nav from './components/Nav';
import Projects from './components/Projects';
import Footer from './components/Footer';
import ThemeContext from './theme-context';
import me from './images/me.webp';
import Photos from './components/Photos';

// 1 = fixed
const PARALLAX_AMOUNT = 4;

const App = () => {
  useEffect(() => {
    // background parallax scroll listener
    const onScroll = () => {
      document.body.style.backgroundPositionY = -window.scrollY / PARALLAX_AMOUNT + 'px';
    };

    window.addEventListener("scroll", onScroll);

    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  // dark theme
  const darkPref = localStorage.getItem('theme') ? localStorage.getItem('theme') === 'dark' : window.matchMedia("(prefers-color-scheme: dark)").matches; // use stored pref or system pref by default
  const [darkMode, setDarkMode] = useState(darkPref);

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', darkMode ? 'dark' : 'light');
    localStorage.setItem('theme', darkMode ? 'dark' : 'light');
  }, [darkMode])

  return (
    <ThemeContext.Provider value={{ theme: darkMode ? 'dark' : 'light', toggleTheme: () => setDarkMode(!darkMode) }}>
      <Nav />
      <div id="about" className="full home">
        <div className="container wrapper">
          <div className="card col-md-7">
            <img className="profile-picture center" src={me} alt="Me" />
            <div className="container">
              <h1 className="center">Jacob Sommer</h1>
              <h2 className="center">Student / Software Developer</h2>
              <p className="center">Hi, I'm Jacob. I'm a second-year at UC Irvine pursuing a BS in Computer Science. I've had a passion for technology ever since I was a child, first learning how to code at 11 years old by developing mods for Minecraft. Since then, I've learned many different programming languages and technologies through hobby projects and school projects I've worked on. Aside from coding, my other hobbies include photography, playing video games, building computers, and playing the guitar. I am always eager to learn!</p>
              <div className="col-sm icons center">
                <a className="fa-stack fa-2x" href="https://github.com/js0mmer" target="_blank" aria-label="github">
                  <span className="fab fa-github fa-stack-1x"></span>
                </a>
                <a className="fa-stack fa-2x" href="https://www.linkedin.com/in/js0mmer/" target="_blank" aria-label="linkedin">
                  <span className="fab fa-linkedin fa-stack-1x"></span>
                </a>
              </div>
            </div>
          </div>
        </div>
        <span className="fa fa-chevron-down fa-2x" aria-hidden="true" onClick={() => document.querySelector('#projects')?.scrollIntoView({ behavior: 'smooth'})}></span>
      </div>
      <Projects />
      <Photos />
      <Footer />
    </ThemeContext.Provider>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
  import Project from './lib/Project.svelte';
  import me from './assets/me.webp';
</script>

<main>
  <div class="container">
    <section class="about">
      <div class="text">
        <h1>Jacob Sommer</h1>
        <p>
          Hi, I'm Jacob. I'm a fourth-year at UC Irvine pursuing a BS in Computer Science. I've had a passion for
          technology ever since I was a child, first learning how to code at 11 years old by developing mods for
          Minecraft. Since then, I've learned many different programming languages and technologies through hobby
          projects and school projects I've worked on. Aside from coding, my other hobbies include photography, playing
          video games, building computers, and playing the guitar. I am always eager to learn!
        </p>
        <div class="socials">
          <a class="button" href="https://www.linkedin.com/in/js0mmer/" target="_blank">
            <span class="fa-brands fa-linkedin fa-lg"></span> LinkedIn
          </a>
          <a class="button" href="https://github.com/js0mmer" target="_blank">
            <span class="fa-brands fa-github fa-lg"></span> GitHub
          </a>
          <a class="button" href="resume.pdf" target="_blank">
            <span class="fa-solid fa-file-pdf fa-lg"></span> Resume
          </a>
        </div>
      </div>
      <div class="img">
        <img src={me} alt="Jacob Sommer" />
      </div>
    </section>
    <section class="projects">
      <h2>Projects</h2>
      <div class="projects-grid">
        <Project
          title="PeterPortal"
          img="peterportal.webp"
          content="An enhanced course catalogue and 4-year planner for UC Irvine students, by UC Irvine students. Developed alongside 5-10 peers under UC Irvine's Information & Computer Sciences Student Council. Leading the project as of September 2023."
          links={[
            {
              title: 'peterportal.org',
              url: 'https://peterportal.org',
              icon: 'fa-solid fa-arrow-up-right-from-square'
            },
            {
              title: 'GitHub',
              url: 'https://github.com/icssc/peterportal-client',
              icon: 'fa-brands fa-github'
            }
          ]}
          tags={['TypeScript', 'React', 'Express', 'MongoDB', 'AWS']}
        />
        <Project
          title="PlayPic"
          img="playpic.webp"
          content="A website that creates a Spotify playlist that matches the mood of the image you upload. Developed with a team of 3 peers at the HackUCI 2022 hackathon."
          links={[
            {
              title: 'DevPost',
              url: 'https://devpost.com/software/hackuci-jwe3al',
              icon: 'fa-solid fa-arrow-up-right-from-square'
            },
            {
              title: 'GitHub',
              url: 'https://github.com/js0mmer/hackuci2022',
              icon: 'fa-brands fa-github'
            }
          ]}
          tags={['JavaScript', 'React', 'Express']}
        />
        <Project
          title="Star Tracker"
          img="startracker.webp"
          content="A barn door star tracker enabling you to take longer exposures of the night sky and capture deep sky objects with a DSLR."
          links={[
            {
              title: 'GitHub',
              url: 'https://github.com/js0mmer/startracker',
              icon: 'fa-brands fa-github'
            }
          ]}
          tags={['Python', 'Raspberry Pi']}
        />
      </div>
    </section>
  </div>
</main>

<style>
  section {
    padding-top: 1em;
  }

  section h1 {
    font-size: 2.25em;
  }

  section h2 {
    font-size: 1.75em;
    margin-bottom: 0.5em;
  }

  .container {
    width: 960px;
    max-width: 100%;
    margin: 0 auto;
    padding: 0.5em;
  }

  .about {
    display: flex;
    flex-direction: row;
    gap: 20px;
  }

  .about .text {
    flex: 2;
  }

  .about .img {
    flex: 1;
    max-width: 150px;
  }

  .about .img img {
    border-radius: 0.5em;
  }

  .socials {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
  }

  .projects-grid {
    display: grid;
    gap: 20px;
  }

  @media screen and (max-width: 768px) {
    .about {
      /* flex-direction: column; */
      flex-flow: column-reverse;
      gap: 0;
    }
  }
</style>
